version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: 0lch4/slownik-backend:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: 0lch4/slownik-frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  db-data:

networks:
  app-network:
